### ISSUE TITLE
Panic on `volt install` command

### ISSUE THREAD

**Issue by MyIsaak** [voltpkg/volt#17]
**Describe the bug**
When entering the command `volt install` the following panic is produced.
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("invalid type: map, expected a string", line: 27, column: 16)', src\utils\src\package.rs:195:49
stack backtrace:
   0:     0x7ff620c9546e - std::backtrace_rs::backtrace::dbghelp::trace
                               at /rustc/a49e38e672c60da788360e088f00ad12353e3913\/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
   1:     0x7ff620c9546e - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/a49e38e672c60da788360e088f00ad12353e3913\/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff620c9546e - std::sys_common::backtrace::_print_fmt
                               at /rustc/a49e38e672c60da788360e088f00ad12353e3913\/library\std\src\sys_common\backtrace.rs:67
   3:     0x7ff620c9546e - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/a49e38e672c60da788360e088f00ad12353e3913\/library\std\src\sys_common\backtrace.rs:46
   4:     0x7ff620cb3c5a - core::fmt::write
                               at /rustc/a49e38e672c60da788360e088f00ad12353e3913\/library\core\src\fmt\mod.rs:1117
   5:     0x7ff620c8cb48 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/a49e38e672c60da788360e088f00ad12353e3913\/library\std\src\io\mod.rs:1667
   6:     0x7ff620c98196 - std::sys_common::backtrace::_print
                               at /rustc/a49e38e672c60da788360e088f00ad12353e3913\/library\std\src\sys_common\backtrace.rs:49
   7:     0x7ff620c98196 - std::sys_common::backtrace::print
                               at /rustc/a49e38e672c60da788360e088f00ad12353e3913\/library\std\src\sys_common\backtrace.rs:36
   8:     0x7ff620c98196 - std::panicking::default_hook::closure$1
                               at /rustc/a49e38e672c60da788360e088f00ad12353e3913\/library\std\src\panicking.rs:210
   9:     0x7ff620c97ca8 - std::panicking::default_hook
                               at /rustc/a49e38e672c60da788360e088f00ad12353e3913\/library\std\src\panicking.rs:227
  10:     0x7ff620c987f5 - std::panicking::rust_panic_with_hook
                               at /rustc/a49e38e672c60da788360e088f00ad12353e3913\/library\std\src\panicking.rs:624
  11:     0x7ff620c983db - std::panicking::begin_panic_handler::closure$0
                               at /rustc/a49e38e672c60da788360e088f00ad12353e3913\/library\std\src\panicking.rs:521
  12:     0x7ff620c95d97 - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure$0,never$>
                               at /rustc/a49e38e672c60da788360e088f00ad12353e3913\/library\std\src\sys_common\backtrace.rs:141
  13:     0x7ff620c98339 - std::panicking::begin_panic_handler
                               at /rustc/a49e38e672c60da788360e088f00ad12353e3913\/library\std\src\panicking.rs:517
  14:     0x7ff620ee5e40 - core::panicking::panic_fmt
                               at /rustc/a49e38e672c60da788360e088f00ad12353e3913\/library\core\src\panicking.rs:93
  15:     0x7ff620ee5f53 - core::result::unwrap_failed
                               at /rustc/a49e38e672c60da788360e088f00ad12353e3913\/library\core\src\result.rs:1617
  16:     0x7ff6202e5624 - enum$<core::result::Result<utils::package::PackageJson,serde_json::error::Error> >::unwrap<utils::package::PackageJson,serde_json::error::Error>
                               at /rustc/a49e38e672c60da788360e088f00ad12353e3913\library\core\src\result.rs:1299
  17:     0x7ff6202fefab - utils::package::PackageJson::from
                               at C:\Users\Isaak\Projects\rust\volt\src\utils\src\package.rs:195
  18:     0x7ff62014fd22 - install::command::impl$0::exec::generator$0
                               at C:\Users\Isaak\Projects\rust\volt\src\install\src\command.rs:72
  19:     0x7ff62014eda1 - core::future::from_generator::impl$1::poll<install::command::impl$0::exec::generator$0>
                               at /rustc/a49e38e672c60da788360e088f00ad12353e3913\library\core\src\future\mod.rs:80
  20:     0x7ff6201b7f7c - core::future::future::impl$1::poll<alloc::boxed::Box<dyn$<core::future::future::Future,assoc$<Output,enum$<core::result::Result<tuple$<>,miette::protocol::DiagnosticReport>, 1, 18446744073709551615, Err> > >,core::marker::Send>,alloc::alloc::Global> >
                               at /rustc/a49e38e672c60da788360e088f00ad12353e3913\library\core\src\future\future.rs:119
  21:     0x7ff61fcf5b80 - volt::commands::impl$1::run::generator$0
                               at C:\Users\Isaak\Projects\rust\volt\src\volt\src\commands.rs:129
  22:     0x7ff61fcf3c11 - core::future::from_generator::impl$1::poll<volt::commands::impl$1::run::generator$0>
                               at /rustc/a49e38e672c60da788360e088f00ad12353e3913\library\core\src\future\mod.rs:80
  23:     0x7ff61fcf89cb - volt::main::generator$0
                               at C:\Users\Isaak\Projects\rust\volt\src\volt\src\main.rs:47
  24:     0x7ff61fcf3cf1 - core::future::from_generator::impl$1::poll<volt::main::generator$0>
                               at /rustc/a49e38e672c60da788360e088f00ad12353e3913\library\core\src\future\mod.rs:80
  25:     0x7ff61fcf47a6 - tokio::park::thread::impl$5::block_on::closure$0<core::future::from_generator::GenFuture<volt::main::generator$0> >
                               at C:\Users\Isaak\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.10.0\src\park\thread.rs:263
  26:     0x7ff61fcf9378 - tokio::coop::with_budget::closure$0<enum$<core::task::poll::Poll<enum$<core::result::Result<tuple$<>,miette::protocol::DiagnosticReport>, 1, 18446744073709551615, Err> > >,tokio::park::thread::impl$5::block_on::closure$0>
                               at C:\Users\Isaak\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.10.0\src\coop.rs:106
  27:     0x7ff61fcf7cee - std::thread::local::LocalKey<core::cell::Cell<tokio::coop::Budget> >::try_with<core::cell::Cell<tokio::coop::Budget>,tokio::coop::with_budget::closure$0,enum$<core::task::poll::Poll<enum$<core::result::Result<tuple$<>,miette::protocol::DiagnosticReport>,
                               at /rustc/a49e38e672c60da788360e088f00ad12353e3913\library\std\src\thread\local.rs:399
  28:     0x7ff61fcf7c0c - std::thread::local::LocalKey<core::cell::Cell<tokio::coop::Budget> >::with<core::cell::Cell<tokio::coop::Budget>,tokio::coop::with_budget::closure$0,enum$<core::task::poll::Poll<enum$<core::result::Result<tuple$<>,miette::protocol::DiagnosticReport>, 1, 1
                               at /rustc/a49e38e672c60da788360e088f00ad12353e3913\library\std\src\thread\local.rs:375
  29:     0x7ff61fcf41e0 - tokio::coop::with_budget
                               at C:\Users\Isaak\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.10.0\src\coop.rs:99
  30:     0x7ff61fcf41e0 - tokio::coop::budget
                               at C:\Users\Isaak\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.10.0\src\coop.rs:76
  31:     0x7ff61fcf41e0 - tokio::park::thread::CachedParkThread::block_on<core::future::from_generator::GenFuture<volt::main::generator$0> >
                               at C:\Users\Isaak\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.10.0\src\park\thread.rs:263
  32:     0x7ff61fcf9aa2 - tokio::runtime::enter::Enter::block_on<core::future::from_generator::GenFuture<volt::main::generator$0> >
                               at C:\Users\Isaak\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.10.0\src\runtime\enter.rs:151
  33:     0x7ff61fcf35cc - tokio::runtime::thread_pool::ThreadPool::block_on<core::future::from_generator::GenFuture<volt::main::generator$0> >
                               at C:\Users\Isaak\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.10.0\src\runtime\thread_pool\mod.rs:71
  34:     0x7ff61fcf9888 - tokio::runtime::Runtime::block_on<core::future::from_generator::GenFuture<volt::main::generator$0> >
                               at C:\Users\Isaak\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.10.0\src\runtime\mod.rs:452
  35:     0x7ff61fcf3a25 - volt::main
                               at C:\Users\Isaak\Projects\rust\volt\src\volt\src\main.rs:51
  36:     0x7ff61fcf6c3b - core::ops::function::FnOnce::call_once<enum$<core::result::Result<tuple$<>,miette::protocol::DiagnosticReport>, 1, 18446744073709551615, Err> (*)(),tuple$<> >
                               at /rustc/a49e38e672c60da788360e088f00ad12353e3913\library\core\src\ops\function.rs:227
  37:     0x7ff61fcf9c3b - std::sys_common::backtrace::__rust_begin_short_backtrace<enum$<core::result::Result<tuple$<>,miette::protocol::DiagnosticReport>, 1, 18446744073709551615, Err> (*)(),enum$<core::result::Result<tuple$<>,miette::protocol::DiagnosticReport>, 1, 1844674407370
                               at /rustc/a49e38e672c60da788360e088f00ad12353e3913\library\std\src\sys_common\backtrace.rs:125
  38:     0x7ff61fcf36e1 - std::rt::lang_start::closure$0<enum$<core::result::Result<tuple$<>,miette::protocol::DiagnosticReport>, 1, 18446744073709551615, Err> >
                               at /rustc/a49e38e672c60da788360e088f00ad12353e3913\library\std\src\rt.rs:63
  39:     0x7ff620c98d56 - core::ops::function::impls::impl$2::call_once
                               at /rustc/a49e38e672c60da788360e088f00ad12353e3913\library\core\src\ops\function.rs:259
  40:     0x7ff620c98d56 - std::panicking::try::do_call
                               at /rustc/a49e38e672c60da788360e088f00ad12353e3913\/library\std\src\panicking.rs:403
  41:     0x7ff620c98d56 - std::panicking::try
                               at /rustc/a49e38e672c60da788360e088f00ad12353e3913\/library\std\src\panicking.rs:367
  42:     0x7ff620c98d56 - std::panic::catch_unwind
                               at /rustc/a49e38e672c60da788360e088f00ad12353e3913\/library\std\src\panic.rs:129
  43:     0x7ff620c98d56 - std::rt::lang_start_internal::closure$2
                               at /rustc/a49e38e672c60da788360e088f00ad12353e3913\/library\std\src\rt.rs:45
  44:     0x7ff620c98d56 - std::panicking::try::do_call
                               at /rustc/a49e38e672c60da788360e088f00ad12353e3913\/library\std\src\panicking.rs:403
  45:     0x7ff620c98d56 - std::panicking::try
                               at /rustc/a49e38e672c60da788360e088f00ad12353e3913\/library\std\src\panicking.rs:367
  46:     0x7ff620c98d56 - std::panic::catch_unwind
                               at /rustc/a49e38e672c60da788360e088f00ad12353e3913\/library\std\src\panic.rs:129
  47:     0x7ff620c98d56 - std::rt::lang_start_internal
                               at /rustc/a49e38e672c60da788360e088f00ad12353e3913\/library\std\src\rt.rs:45
  48:     0x7ff61fcf36af - std::rt::lang_start<enum$<core::result::Result<tuple$<>,miette::protocol::DiagnosticReport>, 1, 18446744073709551615, Err> >
                               at /rustc/a49e38e672c60da788360e088f00ad12353e3913\library\std\src\rt.rs:62
  49:     0x7ff61fcf3ad6 - main
  50:     0x7ff620ee3ce0 - invoke_main
                               at d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  51:     0x7ff620ee3ce0 - __scrt_common_main_seh
                               at d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  52:     0x7ffd2e7954e0 - BaseThreadInitThunk
  53:     0x7ffd2f8e485b - RtlUserThreadStart
```

**To Reproduce**
1. Clone this repo: https://github.com/website-checks/website-checks
2. Go to root directory and run `volt install`
3. See error

**Expected behavior**
A nice response saying all packages have been installed.

**Screenshots**
![image](https://user-images.githubusercontent.com/4984415/131158813-6214c2dc-69f7-46ae-9b98-f8188b0ad566.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Terminal: Powershell Core

Note that I'm on the 'main' branch.

**Comment by XtremeDevX** [comment]
Hi @MyIsaak, I'm currently in the middle of a large refactor of volt 😁, so it's not stable enough for use yet. I will publish an alpha release soon once I get a few of the basic commands working!

**Comment by MyIsaak** [comment]
Ok i was just wanting to try it out. I can wait.
